project:
  type: website
  output-dir: docs  # <-- add this


website:
  title: "Kelun Wang"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: portfolio.qmd
        text: Portfolio
  page-footer:
    center: "Portfolio and analytics writing built with Quarto"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
